#!/bin/sh

# River workstation config

# import the common config script
riverctl spawn ~/.config/river/common.sh

# Autostart programs
riverctl spawn ~/repos/configs/scripts/autostart/workstation-autostart.sh

# Keybindings

# switch focus between outputs with arrow keys
riverctl map normal Super+Control Up focus-output DP-2
riverctl map normal Super+Control Down focus-output DP-1

# switch focus between outputs with vim keys
riverctl map normal Super+Control K focus-output DP-2
riverctl map normal Super+Control J focus-output DP-1

# send the focused view to the next/previous output with arrow keys
riverctl map normal Super+Control+Shift Up send-to-output -current-tags DP-2
riverctl map normal Super+Control+Shift Down send-to-output -current-tags DP-1

# send the focused view to the next/previous output with vim keys
riverctl map normal Super+Control+Shift K send-to-output -current-tags DP-2
riverctl map normal Super+Control+Shift J send-to-output -current-tags DP-1

# enable/disable adaptive sync
riverctl map normal Super+Control A spawn 'kanshictl switch gaming'
riverctl map normal Super+Control V spawn 'kanshictl switch desktop'

# set primary xwayland display
riverctl map normal Super+Control X spawn 'xrandr --output DP-1 --primary'

# open RGB light color switcher
riverctl map normal Super+Shift O spawn ~/repos/configs/scripts/dmenu/rgb-switcher.sh

# set scratchpad terminal dimensions
riverctl rule-add -app-id scratchpad dimensions 1720 1000
