# Colors (Arc-Dark)

# Default colors
[colors.primary]
background = '#383c4a'
foreground = '#d3dae3'

# Normal colors
[colors.normal]
black	= '#4b5164'
red	= '#e14245'
green	= '#5ca75b'
yellow	= '#f6ab32'
blue	= '#4877b1'
magenta	= '#a660c3'
cyan	= '#5294e2'
white	= '#a9a9aa'

# Bright colors
[colors.bright]
black	= '#616981'
red	= '#e16f7e'
green	= '#add488'
yellow	= '#fdc35f'
blue	= '#8ca9bf'
magenta	= '#e2afec'
cyan	= '#73c5e2'
white	= '#fcfcfc'
