#!/bin/sh

# River laptop config

# import the common config script
riverctl spawn ~/.config/river/common.sh

# Autostart
riverctl spawn ~/.config/river/autostart.sh

# input settings
riverctl input pointer-1267-12608-MSFT0001:00_04F3:3140_Touchpad tap enabled

# Keybindings

# laptop volume controls
riverctl map normal None XF86AudioMute spawn 'pulsemixer --toggle-mute'
riverctl map normal None XF86AudioLowerVolume spawn 'pulsemixer --change-volume -5'
riverctl map normal None XF86AudioRaiseVolume spawn 'pulsemixer --change-volume +5'

# laptop brightness controls
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl s 10%-'
riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl s +10%'
