theme = "gruvbox"

[editor]
line-number = "absolute"
mouse = false
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "separator", "version-control", "separator", "file-name", "file-modification-indicator", "read-only-indicator", "spinner"]
right = ["position", "total-line-numbers"]
separator = " | "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
