[[language]]
name = "bash"
formatter = { command = "shfmt" }

[[language]]
name = "nix"
language-servers = [ "nixd", "nil" ]

[[language]]
name = "c"
formatter = { command = "clang-format" }

[language-server.nixd]
command = "nixd"

[language-server.nixd.config.nixd.formatting]
command = ["nixfmt"]

[language-server.nixd.config.nixd.options.home-manager]
expr = "(builtins.getFlake (toString ~/repos/configs/nix)).homeConfigurations.\"joppe@Void-Rig\".options"
