[mgr]
append_keymap = [
{ on = [ "<C-w>" ], run = '''shell --confirm --orphan --
                      cp -f $0 ~/Pictures/background/background.jpg
                      magick $0 -blur 0x7 ~/Pictures/background/blur-background.jpg
                      kill $(pgrep swaybg)
                      swaybg -i $0 -m fill
                    ''' },
  
{ on = [ "<C-x>" ], run = "shell --confirm 'feh --bg-scale $0'", desc = "Sets image as wallpaper with feh" },
]
