#!/bin/sh

# River workstation config

# import the common config script
riverctl spawn ~/.config/river/common.sh

# Keybindings

# switch focus between outputs
riverctl map normal Super+Control Up focus-output DP-2
riverctl map normal Super+Control Down focus-output DP-1

# send the focused view to the next/previous output
riverctl map normal Super+Control+Shift Up send-to-output DP-2
riverctl map normal Super+Control+Shift Down send-to-output DP-1

# enable/disable adaptive sync
riverctl map normal Super+Control A spawn 'kanshictl switch gaming'
riverctl map normal Super+Control V spawn 'kanshictl switch desktop'

# set kitty scratchpad terminal dimensions
riverctl rule-add -app-id scratchpad dimensions 1720 1000
